#!/usr/bin/env bash
# TraceMind ↔ Goose one-command integration (MCP-4).
#
# Mirrors scripts/install_claude_code.sh — same wedge, different host.
# Goose is Block's open-source MCP-native agent. It calls MCP servers
# "extensions" in its config; we register tm-mcp as a stdio extension.
#
# What this does, in order:
#   1. Verifies TraceMind is installed (`tracemind`, `tm-mcp` on PATH).
#   2. Verifies Goose is installed (`goose` on PATH).
#   3. Registers `tm-mcp` as a Goose extension via either the YAML
#      config (~/.config/goose/config.yaml) or, if --project is passed,
#      a project-local override (./.goose/config.yaml).
#   4. Restores the demo fixture so the retraction beat fires immediately.
#   5. Prints the 4-prompt retraction demo script for the user to paste
#      into their next `goose session` invocation.
#
# Usage:
#   ./scripts/install_goose.sh             # user-global install
#   ./scripts/install_goose.sh --project   # register in ./.goose/
#   ./scripts/install_goose.sh --no-demo   # skip fixture restore
#
# Privacy stance: only edits files on your machine and runs local
# commands. Goose's transport here is stdio — no network involved.

set -euo pipefail

SCOPE="user"
RESTORE_DEMO=1

while [ $# -gt 0 ]; do
  case "$1" in
    --project)  SCOPE="project"; shift ;;
    --no-demo)  RESTORE_DEMO=0; shift ;;
    -h|--help)
      sed -n '2,28p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

# --- visual helpers --------------------------------------------------------

bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
red()   { printf '\033[31m%s\033[0m\n' "$*" >&2; }
dim()   { printf '\033[2m%s\033[0m\n' "$*"; }

step() {
  echo
  bold "▸ $*"
}

# --- 1. verify TraceMind ---------------------------------------------------

step "Checking TraceMind install"

if ! command -v tracemind >/dev/null 2>&1; then
  red "tracemind binary not found on PATH."
  echo  "Run scripts/install.sh first."
  exit 1
fi

if ! command -v tm-mcp >/dev/null 2>&1; then
  red "tm-mcp binary not found on PATH."
  echo  "Run scripts/install.sh first."
  exit 1
fi

TM_MCP_PATH="$(command -v tm-mcp)"
green "  tracemind: $(command -v tracemind)"
green "  tm-mcp:    $TM_MCP_PATH"

# --- 2. verify Goose -------------------------------------------------------

step "Checking Goose install"

if ! command -v goose >/dev/null 2>&1; then
  red "goose binary not found on PATH."
  echo  "Install Goose first: https://block.github.io/goose/"
  echo  "  brew install block/goose/goose       # macOS"
  echo  "  curl -fsSL https://github.com/block/goose/releases/latest/download/download_cli.sh | bash"
  exit 1
fi

green "  goose:     $(command -v goose)"

# --- 3. register tm-mcp as a Goose extension -------------------------------

step "Registering tm-mcp with Goose ($SCOPE scope)"

if [ "$SCOPE" = "project" ]; then
  CONFIG_DIR="$PWD/.goose"
else
  CONFIG_DIR="${GOOSE_CONFIG_DIR:-$HOME/.config/goose}"
fi
mkdir -p "$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/config.yaml"

# Goose's extension stanza for a stdio MCP server.
read -r -d '' STANZA <<EOF || true
  tracemind:
    type: stdio
    enabled: true
    cmd: $TM_MCP_PATH
    args: []
    envs: {}
    timeout: 30
    description: "TraceMind — local-only memory layer"
EOF

if [ -f "$CONFIG_FILE" ] && grep -q '^[[:space:]]*tracemind:' "$CONFIG_FILE"; then
  dim  "  $CONFIG_FILE already contains a tracemind extension — leaving it alone."
elif [ -f "$CONFIG_FILE" ]; then
  # Append under extensions: if the key exists, else add the whole block.
  if grep -q '^extensions:' "$CONFIG_FILE"; then
    # Best-effort: append under existing extensions: block. We insert
    # after the extensions: line so the YAML stays valid.
    awk -v stanza="$STANZA" '
      /^extensions:[[:space:]]*$/ { print; print stanza; next }
      { print }
    ' "$CONFIG_FILE" > "$CONFIG_FILE.tmp" && mv "$CONFIG_FILE.tmp" "$CONFIG_FILE"
    green "  appended tracemind under existing extensions: in $CONFIG_FILE"
  else
    {
      echo
      echo "extensions:"
      echo "$STANZA"
    } >> "$CONFIG_FILE"
    green "  added extensions: block with tracemind to $CONFIG_FILE"
  fi
else
  cat > "$CONFIG_FILE" <<EOF
# TraceMind ↔ Goose configuration. Generated by scripts/install_goose.sh.
# Everything below stays local — Goose talks to tm-mcp over stdio.
extensions:
$STANZA
EOF
  green "  wrote fresh $CONFIG_FILE"
fi

# --- 4. restore the demo fixture ------------------------------------------

if [ "$RESTORE_DEMO" -eq 1 ]; then
  step "Restoring demo fixture (so the retraction beat fires immediately)"

  if tracemind demo restore --force >/dev/null 2>&1; then
    green "  fixture restored — 15 entities, 16 triples, 1 contradiction, 9 commitments"
  else
    dim "  tracemind demo restore failed — continuing without fixture."
    dim "  You can run it manually later: tracemind demo restore --force"
  fi
fi

# --- 5. print the 4-beat retraction demo ----------------------------------

step "Done. Try the 4-beat demo in a Goose session"

cat <<'EOF'

The wedge: persistence + context isolation (beats 1–2).
The moat:  contradiction-aware retraction (beat 3).
The loop:  feedback (beat 4).

────────────────────────────────────────────────────────────────────
BEAT 1 — Persistence across sessions (the wedge, part 1)
────────────────────────────────────────────────────────────────────
Set up a work context and start a Goose session:

    tracemind context create "work" --tags work,demo   # one-time
    tracemind context use "work"
    cd ~/code/any-project
    goose session

In the session, paste:

    I switched the demo database from Postgres to SQLite on May 1
    because Postgres needed Docker and SQLite ships embedded. I'm
    committing to keeping it SQLite for the investor demo.

Now /exit out of Goose, open a NEW terminal, cd to a DIFFERENT
directory, and run `goose session` again:

    Why am I using SQLite for the demo?

→ Goose reconstructs the May 1 decision in a fresh session, in a
  different directory. THE WEDGE.

────────────────────────────────────────────────────────────────────
BEAT 2 — Context isolation (the wedge, part 2)
────────────────────────────────────────────────────────────────────
    tracemind context create "personal" --tags personal   # one-time
    tracemind context use "personal"
    goose session

In the session:

    What database am I using for the demo?

→ Goose says it has no relevant memory in personal. NO BLUR.

────────────────────────────────────────────────────────────────────
BEAT 3 — Contradiction-aware retraction (the moat)
────────────────────────────────────────────────────────────────────
    tracemind context use "work"
    goose session

    Actually I'm changing my mind, going back to Postgres for the demo.

→ TraceMind flags the contradiction. Goose surfaces it:
  "You committed on May 1 to keeping it SQLite. Are you sure?"
  THE MOAT.

────────────────────────────────────────────────────────────────────
BEAT 4 — Feedback (the compounding moat)
────────────────────────────────────────────────────────────────────
    Yes, retract the SQLite commitment. The contradiction surface
    was useful.

→ Goose calls memory_feedback {kind: "helpful"}; the bandit
  reinforces this retrieval arm. Over a week of use, TraceMind
  measurably improves on your corpus.

If anything is off, see docs/GOOSE_INTEGRATION.md.

EOF
